// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQAEx92BteJ40Hf2JCjs_LEPuiGyp0Uk8',
    appId: '1:1006100055555:web:3daf6dea53032892857036',
    messagingSenderId: '1006100055555',
    projectId: 'calcsoft-e2f4f',
    authDomain: 'calcsoft-e2f4f.firebaseapp.com',
    storageBucket: 'calcsoft-e2f4f.appspot.com',
    measurementId: 'G-38Q6YLXQGX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYyx6C5ChEJcdMKQslkDeWFU2p3Golj_0',
    appId: '1:1006100055555:android:4688e76af04fbc2b857036',
    messagingSenderId: '1006100055555',
    projectId: 'calcsoft-e2f4f',
    storageBucket: 'calcsoft-e2f4f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFwdMQ-g4CgxT1Omgt36aLgTOQ-BGf-eY',
    appId: '1:1006100055555:ios:64bf32a6861a677d857036',
    messagingSenderId: '1006100055555',
    projectId: 'calcsoft-e2f4f',
    storageBucket: 'calcsoft-e2f4f.appspot.com',
    iosClientId: '1006100055555-pmos1qoogl95s9g83s03lva75vg9i1qk.apps.googleusercontent.com',
    iosBundleId: 'com.example.calcSoft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFwdMQ-g4CgxT1Omgt36aLgTOQ-BGf-eY',
    appId: '1:1006100055555:ios:64bf32a6861a677d857036',
    messagingSenderId: '1006100055555',
    projectId: 'calcsoft-e2f4f',
    storageBucket: 'calcsoft-e2f4f.appspot.com',
    iosClientId: '1006100055555-pmos1qoogl95s9g83s03lva75vg9i1qk.apps.googleusercontent.com',
    iosBundleId: 'com.example.calcSoft',
  );
}
